version: '3'

services:
  frontend:
    build: ./frontend
    container_name: behethKade_frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8000
      REACT_APP_STRIPE_PUBLIC_KEY: "pk_test_51Mz4yYDC8iUflflhhDSZV8ZI3FWHrwkTpJYHQNqDPj169XY2VphykPHgXfNd8HTQFzf9mx3IHGTNio6W5Xl5spwv00tBPWsJAV"
    depends_on:
      - apigateway
    networks:
      - bk  
      
  apigateway:
    build: ./backend/apigateway
    container_name: behethKade_APIGateway
    ports:
      - "8000:8000"
    environment:
      REACT_APP_GATEWAY_PORT: 8000
      REACT_APP_ITEM_SERVICES_URI: http://behethKade_ItemService:4000
      REACT_APP_ORDER_SERVICES_URI: http://behethKade_OrderService:5000
      REACT_APP_PAYMENT_SERVICES_URI: http://behethKade_PaymentService:6000
      REACT_APP_USER_SERVICES_URI: http://behethKade_UserService:7000
    depends_on:
      - userservice
      - itemservice
      - orderservice
      - paymentservice
    networks:
      - bk  

  userservice:
    build: ./backend/userservice
    container_name: behethKade_UserService
    ports:
      - "7000:7000"
    environment:
      REACT_APP_MONGODB_URL: mongodb+srv://Randula98:afRToUlHSo2SYKnQ@cluster.6f3z3g7.mongodb.net/?retryWrites=true&w=majority
      REACT_APP_BACKEND_PORT: 7000
      JWT_SECRET: "ASDsd213we65tr3asaASDFCs+d6a1s651as65df1aASDd"
      EMAIL: "behethkade123@gmail.com"
      PASSWORD: "zjhhuqyjtxbavxtf"
      USER_ID: "24816"
      API_KEY: "TAIQkYrtM8c3zYYQrU4j"     
    networks:
      - bk  

  itemservice:
    build: ./backend/itemservice
    container_name: behethKade_ItemService
    ports:
      - "4000:4000"
    environment:
      REACT_APP_MONGODB_URL: mongodb+srv://Randula98:afRToUlHSo2SYKnQ@cluster.6f3z3g7.mongodb.net/?retryWrites=true&w=majority
      REACT_APP_BACKEND_PORT: 4000
    networks:
      - bk  

  orderservice:
    build: ./backend/orderservice
    container_name: behethKade_OrderService
    ports:
      - "5000:5000"
    environment:
      REACT_APP_MONGODB_URL: mongodb+srv://Randula98:afRToUlHSo2SYKnQ@cluster.6f3z3g7.mongodb.net/?retryWrites=true&w=majority
      REACT_APP_BACKEND_PORT: 5000
      EMAIL: "behethkade123@gmail.com"
      PASSWORD: "zjhhuqyjtxbavxtf"
      USER_ID: "24816"
      API_KEY: "TAIQkYrtM8c3zYYQrU4j"     
    networks:
      - bk  

  paymentservice:
    build: ./backend/paymentservice
    container_name: behethKade_PaymentService
    ports:
      - "6000:6000"
    environment:
      REACT_APP_MONGODB_URL: mongodb+srv://Randula98:afRToUlHSo2SYKnQ@cluster.6f3z3g7.mongodb.net/?retryWrites=true&w=majority
      REACT_APP_BACKEND_PORT: 6000 
      STRIPE_SECRET_KEY: "sk_test_51Mz4yYDC8iUflflhLqwtiM15qwbL1jd2MBABLhMpIUcCwsJG6rQTgNMnCTtfeGCSIViuFZfKjZ6JIfSnEKcQw2R600fTaTYxFs"    
    networks:
      - bk  

networks:
  bk:
    driver: bridge
    
# run below command in terminal
# docker compose up -d 
# docker build -t herbal-medicine-selling-platform-frontend .     