version: "3"
services:

  auth:
    build:
      dockerfile: Dockerfile
      context: ./authService
    container_name: auth-service
    ports:
      - "3001:3001"
    restart: always
    env_file:
      - ./authService/.env

  course:
    build:
      dockerfile: Dockerfile
      context: ./courseService
    container_name: course-service
    ports:
      - "3002:3002"
    restart: always
    env_file:
      - ./courseService/.env

  enrollment:
    build:
      dockerfile: Dockerfile
      context: ./enrollmentService
    container_name: enrollment-service
    ports:
      - "3003:3003"
    restart: always
    env_file:
      - ./enrollmentService/.env

  payment:
    build:
      dockerfile: Dockerfile
      context: ./paymentService
    container_name: payment-service
    ports:
      - "3004:3004"
    restart: always
    env_file:
      - ./paymentService/.env

  notification:
    build:
      dockerfile: Dockerfile
      context: ./notificationService
    container_name: notification-service
    ports:
      - "3005:3005"
    restart: always
    env_file:
      - ./notificationService/.env

  feedback:
    build:
      dockerfile: Dockerfile
      context: ./feedbackService
    container_name: feedback-service
    ports:
      - "3006:3006"
    restart: always
    env_file:
      - ./feedbackService/.env

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    ports:
      - "80:80"
