apiVersion: v1
apiVersion: v1
kind: Secret
metadata:
  name: image-secret
type: Opaque
data:
  PORT: MzAwMQ==  # Base64 encoded value of "3002"
  MONGO_URI: bW9uZ29kYitzcnY6Ly9hZjEyMzphZjEyM0BhZjAuZXRyenU1cS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
  JWT_EXPIRE: MzYwMDAw
  JWT_REFRESH_EXPIRE: MzA=
  JWT_SECRET: Z2loYW4xMjM=
  RABBITMQ_URL: YW1xcDovL3JhYmJpdG1xOjU2NzI=
  